CREATE TABLE CENTER_STANDARDIZATION_COLUMN_DEFINITION(
                                 CNTER_NM TEXT,
                                 CNTER_ID TEXT,
                                 PRODUCT_CD TEXT,
                                 PRODUCT_NM TEXT,
                                 OLD_TABLE_NM TEXT,
                                 DATASET_CD TEXT,
                                 NEW_TABLE_NM TEXT,
                                 IDX TEXT,
                                 IN_COLUMN_NM TEXT,
                                 KOR_COLUMN_NM TEXT,
                                 OUT_COLUMN_NM TEXT,
                                 IN_DATA TEXT,
                                 DOMAIN_TY TEXT,
                                 DOMAIN_NM TEXT,
                                 TY_LEN TEXT,
                                 NOT_NULL TEXT,
                                 CONT TEXT,
                                 DATA_FORMAT TEXT,
                                 COLUMN_FUNC TEXT,
                                 DATA_CONT_FUNC TEXT,
                                 REMARK TEXT,
                                 CREATE_TIME TEXT,
                                 UPDATE_TIME TEXT
                             )
							datascope GLOBAL
							ramexpire 0
							diskexpire 0
							partitionkey None
							partitiondate None
							partitionrange 0;
