CREATE TABLE public.CENTER_STANDARDIZATION_COLUMN_DEFINITION(
                                 CNTER_NM varchar(30),
                                 CNTER_ID char(2) NOT NULL,
                                 PRODUCT_CD char(20),
                                 PRODUCT_NM varchar(200),
                                 OLD_TABLE_NM varchar(50),
                                 DATASET_CD varchar(50),
                                 NEW_TABLE_NM varchar(50) NOT NULL,
                                 IDX varchar(3),
                                 IN_COLUMN_NM varchar(50),
                                 KOR_COLUMN_NM varchar(100),
                                 OUT_COLUMN_NM varchar(50) NOT NULL,
                                 IN_DATA varchar(100),
                                 DOMAIN_TY varchar(10),
                                 DOMAIN_NM varchar(50),
                                 TY_LEN varchar(12),
                                 NOT_NULL varchar(8),
                                 CONT varchar(200),
                                 DATA_FORMAT varchar(30),
                                 COLUMN_FUNC varchar(200),
                                 DATA_CONT_FUNC varchar(200),
                                 REMARK varchar(200),
                                 CREATE_TIME varchar(14),
                                 UPDATE_TIME varchar(14),
                                 PRIMARY KEY (CNTER_ID, PRODUCT_CD ,NEW_TABLE_NM,IDX, OUT_COLUMN_NM,CREATE_TIME)
                             )
