CREATE TABLE CNTR_STDZN_CLMN_DFNTN_TB(
                                 CNTR_NM TEXT,
                                 CNTR_ID TEXT,
                                 PRD_CD TEXT,
                                 PRD_NM TEXT,
                                 PREV_TB_NM TEXT,
                                 DTST_CD TEXT,
                                 NW_TB_NM TEXT,
                                 IDX TEXT,
                                 PREV_CLMN_NM TEXT,
                                 KOR_CLMN_NM TEXT,
                                 NW_CLMN_NM TEXT,
                                 KOR_DMN_LRG_CTGRY TEXT,
                                 KOR_DMN_MDDL_CTGRY TEXT,
                                 KOR_DMN_SMLL_CTGRY TEXT,
								 TYPE_LNTH TEXT,
								 DATA_FRMT TEXT,
                                 NOTNULL_YN TEXT,
                                 MINM_VL TEXT,
								 MAX_VL TEXT,
								 XCPTN_VL TEXT,
                                 CLMN_FUNC TEXT,
                                 DATA_CONT_FUNC TEXT,
                                 RMKS TEXT,
                                 CREATE_TIME TEXT,
                                 UPDATE_TIME TEXT
                             )
							datascope GLOBAL
							ramexpire 0
							diskexpire 0
							partitionkey None
							partitiondate None
							partitionrange 0;
